brave/ads-ui

- package-lock.json
- package.json
- src/user/settings/Settings.tsx
- src/user/settings/queries/Settings.queries.ts
> Revert "Revert "Stage""

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
> Fix GitHub action warning

- src/user/views/adsManager/views/advanced/components/reviewForm/library/ReviewForm.queries.ts
Re https://github.com/brave/ads-serve/issues/1853
> When creating a campaign, set the format to PUSH_NOTIFICATION

- src/user/components/navbar/Navbar.tsx
- remove non-working Help Center and Messages
- only show New Campaign for an allow list of advertisers
Re https://github.com/brave/ads-admin-dashboard/issues/391
> Tidy up top nav bar

- src/user/analytics/analyticsOverview/AnalyticsOverview.tsx
- src/user/analytics/analyticsOverview/lib/AnalyticsOverview.queries.ts
> display a message rather than blank screen for non-supported campaign formats

- package-lock.json
> fix vulnerable dependencies

- package-lock.json
> production release: fix vulnerable dependencies

- src/components/Conversion/ConversionFields.tsx
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
- src/validation/CampaignSchema.tsx
allows for form to submit when observation window is present
> observation window fixes, better validation verbiage

- src/actions/auth/auth.interface.ts
- src/state/context.ts
- src/user/User.tsx
- src/user/analytics/analyticsOverview/components/ReportUtils.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/components/navbar/Navbar.tsx
- src/user/components/sidebar/Sidebar.tsx
Use feature flags instead of hardcoded ID.
> advertiser permissions self service

- src/components/Campaigns/CampaignDateRange.tsx
- src/components/Conversion/ConversionFields.tsx
- src/components/List/CustomListItemText.tsx
- src/components/Location/LocationPicker.tsx
- src/components/Platform/PlatformPicker.tsx
- src/components/Url/UrlResolver.tsx
- src/form/DateFieldHelpers.tsx
- src/form/FormikHelpers.tsx
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/adSet/fields/DetailsField.tsx
- src/user/views/adsManager/views/advanced/components/campaign/CampaignFields.tsx
- src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
- src/user/views/adsManager/views/advanced/components/campaign/fields/LocationField.tsx
- src/user/views/adsManager/views/advanced/components/review/Review.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/CampaignReview.tsx
- src/validation/CampaignSchema.test.ts
- src/validation/CampaignSchema.tsx
General feedback for the MVP Of V1
> Version One Feedback

- src/components/Campaigns/Status.tsx
- src/components/EnhancedTable/renderers.tsx
- src/components/Switch/OnOff.tsx
- src/user/User.tsx
- src/user/adSet/AdSetList.tsx
- src/user/ads/AdList.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/components/sidebar/Sidebar.tsx
- src/user/library/index.ts
- src/util/isAfterEndDate.ts
Adds functionality to pause and activate campaigns or creatives based on their state and the campaigns end date.
> Pause & Activate: Campaigns + Creative

- src/components/EnhancedTable/renderers.tsx
- src/graphql/ad-set.generated.tsx
- src/graphql/ad-set.graphql
- src/graphql/advertiser.generated.tsx
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/types.ts
- src/user/User.tsx
- src/user/adSet/AdSetList.tsx
Add functionality to pause / activate ad sets
> Pause / Activate Ad Sets

- src/App.tsx
- src/user/User.tsx
- src/user/analytics/AnalyticsOverview.tsx
- src/user/analytics/analyticsOverview/lib/overview.library.ts
- src/user/library/index.ts
Noticed I could not get on overview route. Addresses that.
Also adds adset id to request, which is needed
> routing adjustments

- src/user/components/sidebar/Sidebar.tsx
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
- src/validation/CampaignSchema.tsx
Was passing in document node, but not using
> fix document node

- src/components/EnhancedTable/renderers.tsx
- src/user/User.tsx
- src/user/adSet/AdSetList.tsx
- src/user/ads/AdList.tsx
- src/user/campaignList/CampaignList.tsx
It might be neater to completely hide the column in these cases but this is better than showing the button.
> Don't show on/off toggle unless advertiser has edit rights

- src/components/Conversion/ConversionFields.tsx
- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
- src/validation/CampaignSchema.tsx
Fixing some validation requests
> Validation changes

- src/components/Conversion/ConversionFields.tsx
- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
- src/validation/CampaignSchema.tsx
> Production Release 2023-03-21

- src/components/Segment/SegmentPicker.tsx
- src/form/FormikHelpers.tsx
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/review/components/AdReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
> Audience selection updates

- src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
Price reset every time you came back to page, this fixes
> remove useEffect

- src/actions/auth/auth.interface.ts
- src/components/Campaigns/CampaignDateRange.tsx
- src/components/EnhancedTable/renderers.tsx
- src/components/Segment/SegmentPicker.tsx
- src/form/FormikHelpers.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/campaign.graphql
- src/graphql/types.ts
- src/user/adSet/AdSetList.tsx
- src/user/ads/AdList.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/adSet/fields/DetailsField.tsx
- src/user/views/adsManager/views/advanced/components/campaign/CampaignFields.tsx
- src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
- src/user/views/adsManager/views/advanced/components/form/components/BaseForm.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/CampaignReview.tsx
- src/validation/CampaignSchema.test.ts
- src/validation/CampaignSchema.tsx
Features: 
- #672
- #668 
- #671
Bug:
- #675
> Production Release 2023-03-23

- src/components/Url/UrlResolver.tsx
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
Bug in the segment edit view. If untargeted did not populate correctly.
> Fix bug in segment

- src/App.tsx
Better retrieval of advertiser
> correct advertiser

- src/App.tsx
> Production Release 2023-04-05 (2)

- src/components/Campaigns/CampaignAgeFilter.tsx
- src/components/EnhancedTable/renderers.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/advertiser.graphql
- src/graphql/campaign.generated.tsx
- src/graphql/campaign.graphql
- src/graphql/types.ts
- src/user/User.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/library/index.ts
Dependent on: https://github.com/brave/ads-serve/pull/2878
---
> filter campaigns

- src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
> fix budget validation

- src/components/Url/UrlResolver.tsx
- src/validation/CampaignSchema.tsx
Feedback has shown it is not obvious enough url is validating:
---
> improve validation

- src/user/views/adsManager/types/index.ts
- src/validation/CampaignSchema.test.ts
Updates default pacing strategy
> update default model

- src/auth/lib/index.ts
- src/user/User.tsx
- src/user/analytics/analyticsOverview/lib/csv.library.ts
- src/user/library/index.ts
> include credentials

- package-lock.json
- package.json
Addresses: https://github.com/advisories/GHSA-f9xv-q969-pqx4
> override yaml version

- src/auth/views/Login.tsx
- src/auth/views/MagicLink.tsx
> fix spelling

- src/components/Campaigns/Status.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/advertiser.graphql
- src/graphql/creative.generated.tsx
- src/graphql/creative.graphql
- src/graphql/types.ts
- src/user/analytics/AnalyticsOverview.tsx
- src/user/analytics/analyticsOverview/components/EngagementHeader.tsx
- src/user/analytics/analyticsOverview/reports/creative/CreativeOverview.tsx
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
> update an ad when it is not active / paused

- src/auth/hooks/mutations/useSignIn.ts
- src/auth/lib/index.ts
> require username and password before calling api

- .github/workflows/sanity-check.yml
- README.md
- package-lock.json
- package.json
- src/auth/lib/index.ts
- src/auth/views/Login.tsx
- src/auth/views/MagicLink.tsx
- src/components/Campaigns/Status.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/advertiser.graphql
- src/graphql/creative.generated.tsx
- src/graphql/creative.graphql
- src/graphql/types.ts
- src/user/analytics/AnalyticsOverview.tsx
- src/user/analytics/analyticsOverview/components/EngagementHeader.tsx
- src/user/analytics/analyticsOverview/reports/creative/CreativeOverview.tsx
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
Features:
- #770 
Fixes:
- #769 
- #758 
- #762
- #759 
... Various dependency updates ...
> Production Release 2023-05-15

- src/graphql/advertiser.generated.tsx
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/campaign.graphql
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
- src/user/views/adsManager/views/advanced/components/review/Review.tsx
Allows for BAT to be chosen as a Currency Option
---
> Add BAT as currency option

- src/user/campaignList/CampaignList.tsx
- src/validation/CampaignSchema.tsx
No reason to have someone click into reporting before campaign is live, fixes that
> fix when reporting can be seen

- src/components/Error/ErrorDetail.tsx
- src/user/analytics/AnalyticsOverview.tsx
- src/user/settings/Settings.tsx
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
- src/user/views/user/MainView.tsx
Ads Error messages in areas that did not previously have them.
> Add error messages in key areas

- src/user/views/adsManager/views/advanced/components/ads/AdField.tsx
State can be undefined, and page becomes unable to render.
> Fix state bug

- src/App.tsx
- src/auth/hooks/mutations/useRegister.ts
- src/auth/lib/index.ts
- src/auth/registration/AddressField.tsx
- src/auth/registration/AdvertiserField.tsx
- src/auth/registration/AdvertiserRegistered.tsx
- src/auth/registration/NameField.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/RegistrationSchema.tsx
- src/auth/registration/StepsButton.tsx
- src/auth/registration/types.ts
- src/auth/views/MagicLink.tsx
- src/auth/views/components/AuthContainer.tsx
- src/components/Card/CardContainer.tsx
- src/components/Conversion/ConversionFields.tsx
- src/components/Country/CountryPicker.tsx
- src/components/Country/useCountries.ts
- src/form/FormikHelpers.tsx
- src/user/User.tsx
- src/user/views/adsManager/views/advanced/components/completionForm/CompletionForm.tsx
- src/validation/CampaignSchema.tsx
Allows for registration for the self service ads platform.
---
---
> Self Service Registration

- src/auth/registration/AddressField.tsx
> fix: remove verbiage

- src/checkout/hooks/useValidatePaymentSession.ts
- src/checkout/lib/index.ts
- src/user/views/adsManager/views/advanced/components/completionForm/CompletionForm.tsx
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
- src/user/views/user/MainView.tsx
Dependent on: https://github.com/brave/ads-serve/pull/3106
Correlates to backend changes where new creatives for a campaign get updated as long as it is paid.
> fix: allow for new creatives to be updated

- src/user/views/adsManager/views/advanced/components/review/components/AdReview.tsx
Errors can be undefined, causes form not to display in some cases
> fix: correctly type error state

- src/auth/registration/AdvertiserRegistered.tsx
- src/user/components/navbar/Navbar.tsx
- src/user/views/adsManager/views/advanced/components/form/components/BaseForm.tsx
Adds contact email to areas in dashboard
> feat: add contact email

- package-lock.json
- package.json
Overrides semver to fix: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
> fix: override semvar version

- package-lock.json
- package.json
- src/auth/lib/index.ts
Fixes an issue where emails with periods or plus signs are not recognized when logging in
> fix: encode magic link email

- package-lock.json
- package.json
- src/auth/lib/index.ts
> Production Release: 2023-07-06

- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
Fixes a case where manual_bat will not update creative states.
> fix: Add campaign ID to param

- src/user/campaignList/CampaignList.tsx
Removed the edit button when refactoring reporting, this adds it back.
---
> fix: add back edit button

- src/components/Card/CardContainer.tsx
Containers need 3 padding at minimum
> fix: containers need padding

- codegen.ts
- package-lock.json
- package.json
- src/graphql/ad-set.generated.tsx
- src/graphql/ad-set.graphql
- src/graphql/campaign.generated.tsx
- src/graphql/types.ts
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
re: https://github.com/brave/ads-serve/issues/2195
> feat: switch to using simplified pricing api

- src/user/analytics/analyticsOverview/components/LiveFeed.tsx
Adds conversions to key stats, if available
> feat: add conversions to key metrics, if they exist

- src/user/analytics/analyticsOverview/components/LiveFeed.tsx
Adds general CPA if conversions exist
> fix: add cpa with conversions

- src/auth/registration/AdvertiserRegistered.tsx
- src/auth/registration/Register.tsx
- src/components/AppBar/LandingPageAppBar.tsx
Adjusts margin and changes resources link
> fix: change link, adjust margin

- src/graphql/analytics-overview.generated.tsx
- src/graphql/analytics-overview.graphql
- src/graphql/types.ts
- src/user/analytics/analyticsOverview/hooks/usePersistMetricFilter.ts
- src/user/analytics/analyticsOverview/reports/campaign/EngagementsOverview.tsx
Allows for the filter criteria in the dashboard to be persisted in localstorage
> feat: persist metric filter preference

- src/form/FormikHelpers.tsx
- src/user/ads/NotificationAd.tsx
> fix: make sure text boxes have correct width

- src/form/FormikHelpers.tsx
- src/user/ads/NotificationAd.tsx
> Production Release 2023-08-04

- src/user/views/adsManager/views/advanced/components/completionForm/CompletionForm.tsx
Fixes container aligning to left, needs to be in center
> fix: add margin to complete page

- src/components/Campaigns/CloneCampaign.tsx
- src/form/fragmentUtil.ts
- src/user/User.tsx
- src/user/campaignList/CampaignList.tsx
> Production Release 2023-08-17

- .eslintignore
- codegen.ts
- src/components/EnhancedTable/renderers.tsx
- src/graphql/ad-set.generated.tsx
- src/graphql/ad-set.graphql
- src/graphql/advertiser.generated.tsx
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/common.generated.tsx
- src/graphql/creative.generated.tsx
- src/graphql/types.ts
- src/graphql/url.generated.tsx
- src/graphql/user.generated.tsx
- tsconfig.json
Removes __typename form being generated
> chore: don't generate __typename for graphql

- src/components/Campaigns/CampaignAgeFilter.tsx
- src/components/Campaigns/CloneCampaign.tsx
- src/components/EnhancedTable/renderers.tsx
- src/state/context.ts
- src/user/User.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
- src/user/views/user/CampaignView.tsx
- tsconfig.json
Queries are not refetching appropriately when creating or editing campaigns, this resolves
> fix: refetch queries correctly

- .eslintignore
- codegen.ts
- src/components/Campaigns/CampaignAgeFilter.tsx
- src/components/Campaigns/CloneCampaign.tsx
- src/components/EnhancedTable/renderers.tsx
- src/graphql/ad-set.generated.tsx
- src/graphql/ad-set.graphql
- src/graphql/advertiser.generated.tsx
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/common.generated.tsx
- src/graphql/creative.generated.tsx
- src/graphql/types.ts
- src/graphql/url.generated.tsx
- src/graphql/user.generated.tsx
- src/state/context.ts
- src/user/User.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
- src/user/views/user/CampaignView.tsx
- tsconfig.json
> Production Release 2023-08-24

- src/components/Campaigns/CloneCampaign.tsx
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/user/CampaignView.tsx
Fixes for moving managed clients to self-serve
> fix: clone campaign created in self-serve, remove deleted ads in edit

- src/user/library/index.test.ts
- src/user/library/index.ts
Updates new campaign defaults of `perDay` and `totalMax`
> fix: update perDay & totalMax defaults

- package-lock.json
- package.json
- src/user/library/index.test.ts
- src/user/library/index.ts
> Production Release 2023-09-21

- src/graphql/ad-set.generated.tsx
- src/graphql/ad-set.graphql
- src/graphql/campaign.generated.tsx
- src/graphql/types.ts
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
Front end of: https://github.com/brave/ads-serve/issues/3342
> chore: set price at the Ad Set level

- src/components/Creatives/NewsPreview.tsx
- src/user/ads/InlineContentAd.tsx
Allows for certain advertisers to specify name
> fix: allow advertiser name

- src/form/fragmentUtil.ts
- src/graphql/types.ts
Missed campaign clone when moving adSet price.
> fix: campaign clone

- src/form/fragmentUtil.ts
- src/user/library/index.test.ts
- src/user/library/index.ts
Removes creativeSetId and sets correct default
> fix: dont include creative set id

- src/form/fragmentUtil.ts
- src/graphql/types.ts
- src/user/library/index.test.ts
- src/user/library/index.ts
> Production Release 2023-09-27

- package-lock.json
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
Fixes database relationship error
---
https://github.com/brave/ads-ui/assets/48930920/d5b87c05-65c3-4080-9929-de4a02287aaf
> fix: include id if available

- src/graphql/advertiser.generated.tsx
- src/graphql/advertiser.graphql
- src/graphql/types.ts
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/campaign/fields/FormatField.tsx
- src/validation/CampaignSchema.test.ts
- src/validation/CampaignSchema.tsx
Resolves changes made by: https://github.com/brave/ads-serve/pull/3410
> fix: update price naming

- renovate.json
- src/components/EnhancedTable/renderers.tsx
- src/components/Switch/OnOff.tsx
- src/user/adSet/AdSetList.tsx
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/adSet/AdSetFields.tsx
- src/util/displayState.ts
Allows inline pause of ad set.
---
> feat: allow pause inline on Ad Set

- src/auth/lib/index.ts
- src/auth/registration/AddressField.tsx
- src/auth/registration/NameField.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/types.ts
- src/validation/RegistrationSchema.tsx
Add's a section that gets a description of the business during registration
---
> feat: add a description section, improve verbiage

- src/user/reporting/csv.library.tsx
Updates CSV parse to be inline with backend
> fix: update csv parse

- package-lock.json
- src/user/reporting/csv.library.tsx
> Production Release 2023-10-03 (2)

- src/auth/components/AdvertiserAgreed.tsx
Fixes situations where it does not make sense to show prepayment message
---
https://github.com/brave/ads-ui/assets/48930920/4ce412ac-4660-4a86-8dc0-93aac5f85592
> fix: agree page

- src/auth/components/AdvertiserAgreed.tsx
- src/user/analytics/renderers/index.tsx
> Production Release 2023-10-04

- src/components/Drawer/MiniSideBar.tsx
- src/user/views/adsManager/views/advanced/components/adSet/NewAdSet.tsx
> Prod Release 2023-10-05

- .github/workflows/maintain-prod-release-pr.yaml
Updates prod pr description + title
> chore: add prod PR maintenance script

- src/auth/components/AdvertiserAgreed.tsx
- src/auth/context/auth.interface.ts
- src/auth/hooks/queries/useAdvertiser.ts
- src/auth/lib/index.ts
- src/components/Drawer/MiniSideBar.tsx
- src/components/Navigation/Navbar.tsx
- src/components/Navigation/NewCampaignButton.tsx
- src/components/Navigation/NewCreativeButton.tsx
- src/components/Navigation/NewImageButton.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/advertiser.graphql
- src/graphql/types.ts
- src/user/User.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/views/user/CampaignView.tsx
Front end of: https://github.com/brave/ads-serve/pull/3433
> chore: simplify campaign management flags

- src/components/Creatives/CreativeStatusSwitch.tsx
Fix order of words in status switch
> fix: status switch

- src/user/library/index.test.ts
- src/user/library/index.ts
Makes frequency caps same across ad sets and campaigns
> fix: make frequency caps the same

- src/user/library/index.test.ts
- src/user/library/index.ts
> Production Release 2023-10-26

- src/components/Location/LocationPicker.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/common.generated.tsx
- src/graphql/creative.generated.tsx
- src/graphql/types.ts
- src/graphql/url.generated.tsx
- src/graphql/user.generated.tsx
Resolves issues from not requiring geocode name
> fix: location picker

- src/auth/hooks/mutations/useRegister.ts
- src/auth/lib/index.ts
- src/auth/registration/AddressField.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/types.ts
- src/form/FormikHelpers.tsx
Resolves https://github.com/brave/ads-ui/issues/982
---
> feat: add marketing opt in checkbox

- src/auth/registration/Register.tsx
- src/components/Route/RouteSelectionButton.tsx
Fixes when you press next while on personal info screen, but are brought to managed form
> fix: make sure navigation on form is consistent

- src/user/analytics/analyticsOverview/components/MetricSelect.tsx
Resolves https://github.com/brave/ads-ui/issues/989
---
> feat: add tooltips

- src/auth/registration/AccountChoice.tsx
Resolves https://github.com/brave/ads-ui/issues/1003
---
> fix: update copy on signup

- src/components/Creatives/CreativeList.tsx
- src/components/Creatives/CreativeType.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/campaign/fields/FormatField.tsx
- src/util/campaign.ts
- src/validation/CampaignSchema.test.ts
Resolves https://github.com/brave/ads-ui/issues/1017
---
---
> fix: update ad names

- src/graphql/ad-set.generated.tsx
- src/graphql/ad-set.graphql
- src/graphql/analytics-overview.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/campaign.graphql
- src/graphql/types.ts
- src/user/adSet/AdSetList.tsx
- src/user/ads/AdList.tsx
- src/user/analytics/renderers/index.tsx
- src/user/views/user/AdDetailTable.tsx
Resolves https://github.com/brave/ads-ui/issues/1024
---
> feat: show deleted ads in metrics

- audit-resolve.json
Audit error for a dev dependency that currently does not seem to have a solution
> chore(deps): temporarily suppress warning

- src/components/Button/AlwaysOnFormButton.tsx
- src/components/Drawer/MiniSideBar.tsx
- src/user/views/user/CampaignReportView.tsx
Resolves https://github.com/brave/ads-ui/issues/1020
---
> feat: add persistent feedback button

- src/auth/lib/index.ts
- src/auth/registration/AddressField.tsx
- src/auth/registration/MarginedDivider.tsx
- src/auth/registration/MarketingOptIn.tsx
- src/auth/registration/NameField.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/types.ts
- src/components/AppBar/LandingPageAppBar.tsx
- src/components/Country/CountryPicker.tsx
- src/components/Drawer/MiniSideBar.tsx
- src/form/FormikHelpers.tsx
- src/user/settings/Settings.tsx
- src/validation/RegistrationSchema.tsx
Resolves https://github.com/brave/ads-ui/issues/1036
---
https://github.com/brave/ads-ui/assets/48930920/81eea730-b060-4702-a674-022ef3d14bcc
> feat: adjust registration copy and flow

- src/auth/registration/NameField.tsx
- src/auth/registration/types.ts
> Production Release 2024-01-31

- src/auth/lib/index.ts
Currently, signups are registered but not for anything in particular
> fix: need to specify brave ads for newsletter

- src/checkout/lib/index.ts
> Production Release 2024-02-01

- src/auth/components/AdvertiserAddress.tsx
- src/auth/components/AdvertiserAgreed.tsx
- src/auth/components/AdvertiserDetailsForm.tsx
- src/auth/components/types.ts
- src/auth/lib/index.ts
- src/auth/registration/NameField.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/types.ts
- src/components/Country/CountryPicker.tsx
- src/graphql/advertiser.generated.tsx
- src/graphql/advertiser.graphql
- src/graphql/types.ts
- src/user/User.tsx
- src/validation/AdvertiserSchema.tsx
- src/validation/RegistrationSchema.tsx
Improvement of: https://github.com/brave/ads-ui/issues/1036
---
https://github.com/brave/ads-ui/assets/48930920/13636c09-ca75-4a01-b6e8-7fafcf59dbc5
> feat: move address step to after approval

- src/user/views/user/AdDetailTable.tsx
fixes blank screen in reporting
> fix: ensure row has id

- src/graphql/analytics-overview.generated.tsx
- src/graphql/analytics-overview.graphql
> fix: add id to engagements

- src/graphql/analytics-overview.generated.tsx
- src/graphql/analytics-overview.graphql
> Production Release 2024-02-06

- package-lock.json
- package.json
Seems to be a caching issue in apollo 3.9.2. Downgrade to 3.8.10 when the issue did not exist.
> fix: downgrade apollo

- src/user/views/adsManager/views/advanced/components/adSet/fields/PickerFields.tsx
- src/user/views/adsManager/views/advanced/components/review/components/CampaignReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/ReviewField.tsx
Resolves news requiring segments
> fix: make sure news is untargeted

- src/user/views/adsManager/views/advanced/components/adSet/fields/PickerFields.tsx
- src/user/views/adsManager/views/advanced/components/review/components/CampaignReview.tsx
- src/user/views/adsManager/views/advanced/components/review/components/ReviewField.tsx
> Production Release 2024-02-07

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
- src/App.tsx
- src/ErrorBoundary.tsx
- src/components/Error/ErrorDetail.tsx
- src/user/User.tsx
- src/util/version.ts
Adds current sha version as well as error boundry to make debugging issues easier.
> chore: add error boundry and current build info

- src/auth/components/AdvertiserAddress.tsx
- src/auth/components/AdvertiserDetailsForm.tsx
- src/validation/AdvertiserSchema.tsx
> Production Release 2024-02-13

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/user/views/adsManager/views/advanced/components/adSet/fields/AdSetAds.tsx
- src/user/views/adsManager/views/advanced/components/adSet/fields/ConversionField.tsx
- src/user/views/adsManager/views/advanced/components/adSet/fields/PickerFields.tsx
- src/user/views/adsManager/views/advanced/components/campaign/CampaignSettings.tsx
- src/user/views/adsManager/views/advanced/components/campaign/components/BillingModelSelect.tsx
- src/user/views/adsManager/views/advanced/components/campaign/fields/FormatField.tsx
- src/user/views/adsManager/views/advanced/components/campaign/fields/PaymentMethodField.tsx
Fixes missing spaces introduces by localization
> fix: spacings for learn more button

- src/auth/registration/MarketingOptIn.tsx
- src/validation/AdvertiserSchema.tsx
Resolves links opening internally
> fix: make sure link opens externally

- renovate.json
Groups Apollo changes into their own PR's
> chore: separate Apollo changes

- src/locales/en.po
Partial miss in localization file
> fix: localization was left partially empty

- src/user/analytics/analyticsOverview/components/MetricSelect.tsx
- src/util/bignumber.ts
> fix: make sure autocomplete has correct label

- src/theme.tsx
- src/user/analytics/analyticsOverview/components/MetricSelect.tsx
- src/util/bignumber.ts
> Production Release 2024-02-22

- src/auth/hooks/mutations/useGetLink.ts
- src/checkout/hooks/useCreatePaymentSession.ts
- src/components/Assets/ImagePreview.tsx
- src/components/Assets/hooks/useGetImagePreviewUrl.ts
- src/components/Assets/hooks/useUploadFile.ts
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/user/hooks/useAdvertiserWithPrices.tsx
- tsconfig.json
Resolves issue where react claims hook order is not respected with certain lingui calls
> fix: make sure hook order is respected

- .eslintrc.js
- README.md
- src/auth/components/AdvertiserAddress.tsx
- src/auth/components/AdvertiserAgreed.tsx
- src/auth/components/AdvertiserDetailsForm.tsx
- src/auth/components/types.ts
- src/components/Button/LearnMoreButton.tsx
- src/components/Country/CountryPicker.tsx
- src/form/FormikButton.tsx
- src/form/FormikHelpers.tsx
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/validation/AdvertiserSchema.tsx
Resolves https://github.com/brave/ads-ui/issues/1088
---
> feat: update verbiage and look of advertiser agreement page

- .husky/pre-commit
- src/components/Assets/ImagePreview.tsx
- src/components/Creatives/NewsPreview.tsx
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/user/ads/NotificationAd.tsx
Resolves https://github.com/brave/ads-ui/issues/1106
---
Resolves https://github.com/brave/ads-ui/issues/1104
> feat: news v2, warning text on notification

- src/components/Button/ContainedDashboardButton.tsx
- src/components/Creatives/CreativeCampaigns.tsx
- src/graphql/ad-set.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/creative.generated.tsx
- src/graphql/creative.graphql
- src/graphql/types.ts
- src/user/analytics/analyticsOverview/reports/campaign/EngagementsOverview.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/views/user/CampaignReportView.tsx
> fix: temp exclude search from reporting

- src/components/Button/ContainedDashboardButton.tsx
- src/components/Creatives/CreativeCampaigns.tsx
- src/graphql/ad-set.generated.tsx
- src/graphql/campaign.generated.tsx
- src/graphql/creative.generated.tsx
- src/graphql/creative.graphql
- src/graphql/types.ts
- src/user/analytics/analyticsOverview/reports/campaign/EngagementsOverview.tsx
- src/user/campaignList/CampaignList.tsx
- src/user/views/user/CampaignReportView.tsx
> Production Release 2024-03-08

- src/auth/hooks/mutations/useRegister.ts
- src/auth/lib/index.ts
- src/auth/registration/BrowserRegister.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/SearchRegister.tsx
And tidy up some of the objects now the registration endpoint is live in staging.
Remove the "legacy" flow.
> fix: update to use new registration flow

- src/auth/hooks/mutations/useRegister.ts
- src/auth/lib/index.ts
- src/auth/registration/BrowserRegister.tsx
- src/auth/registration/Register.tsx
- src/auth/registration/SearchRegister.tsx
> Production Release 2024-03-11

- src/components/Button/AlwaysOnFormButton.tsx
- src/components/Route/RouteSelectionButton.tsx
Fixes some spacing issues with translations
> fix: two localization oddities

- src/components/Campaigns/Status.tsx
- src/user/ads/AdList.tsx
- src/user/campaignList/CampaignList.tsx
- src/util/displayState.ts
- src/util/isAfterEndData.test.ts
- src/util/isAfterEndDate.ts
And rename the function to make it clearer which way round it is asking the question.
> fix: correctly display campaign status

- .github/workflows/deploy-to-staging.yml
Allows for versions of application to be deployed to staging for tests
> fix: allow staging deploy overrides

- lingui.config.ts
- src/App.tsx
- src/i18n.ts
- src/index.tsx
- src/locales/test.po
- src/user/User.tsx
Fixes issue where dynamic loading slows down the app
---
https://github.com/brave/ads-ui/assets/48930920/1b536a52-575b-4635-948c-3c0870819ab0
> fix: load localization more efficiently

- src/i18n.ts
- src/index.tsx
- src/theme.tsx
- src/user/campaignList/CampaignList.tsx
Fixes issue with grid localization and filtering
---
https://github.com/brave/ads-ui/assets/48930920/0b750ace-7c57-477e-9155-09d11630cdf2
> fix: grid localization

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
Resolves https://github.com/brave/ads-ui/issues/1148
> fix: sync static directory to have more long lived headers

- .github/workflows/deploy-to-production.yml
- .github/workflows/deploy-to-staging.yml
fixes issue in https://github.com/brave/ads-ui/pull/1149
> fix: include cd in build step

- .gitattributes
- src/auth/registration/MarketingChannel.tsx
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
Resolves https://github.com/brave/ads-ui/issues/1112
> feat: add more marketing-channel resources

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
> feat: add Portuguese translations

- src/components/Creatives/CreativeSpecificPreview.tsx
- src/user/ads/AdsExistingAd.tsx
- src/user/ads/filterCreativesByCampaignFormat.ts
- src/user/campaignList/CampaignList.tsx
- src/user/views/adsManager/views/advanced/components/adSet/fields/AdSetAds.tsx
Resolves issue where mix of creatives can show in review screen
> fix: show accurate creatives in review screen

- src/auth/registration/RegistrationContainer.tsx
> Production Release 2024-05-23

- src/auth/views/LandingPage.tsx
> Production Release 2024-06-03

- src/user/campaignList/CampaignList.tsx
Currently the filter is not working as intended, will remove it for now
> fix: remove default filter

- src/components/Conversion/ConversionDisplay.tsx
- src/components/Conversion/ConversionFields.tsx
- src/form/fragmentUtil.ts
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/adSet/AdSetFields.tsx
- src/user/views/adsManager/views/advanced/components/adSet/fields/ConversionField.tsx
- src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
This reverts commit 738ece934d68083156f2e8d9878a73ee8b5aa162.
> revert: remove conversion setup (#1237)

- src/components/AppBar/LandingPageAppBar.tsx
- src/components/Navigation/AccountMenu.tsx
- src/components/Navigation/Navbar.tsx
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/user/settings/NewKeyPairModal.tsx
- src/user/settings/Settings.tsx
Resolves https://github.com/brave/ads-ui/issues/1243
---
https://github.com/brave/ads-ui/assets/48930920/42aaa98c-2b10-42eb-b7f7-ba994b48e89e
> feat: improve account choice experience

- src/components/Switch/OnOff.tsx
- src/user/views/adsManager/views/advanced/components/adSet/AdSetFields.tsx
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
Resolves issue where toggle cannot be used
> fix(toggle): include ad set id when unpausing

- src/search/preview/SearchPreviewResults.tsx
- src/search/preview/SummaryPanel.tsx
- src/search/preview/data.ts
- src/user/library/format.test.ts
- src/user/library/format.ts
Depends on https://github.com/brave/ads-serve/pull/4113
> feat(search): add in estimated weekly results

- src/components/Datagrid/renderers.tsx
- src/form/fragmentUtil.ts
- src/graphql-client/graphql.ts
- src/graphql/ads-serve.graphql.schema.json
- src/user/library/index.test.ts
- src/user/views/adsManager/types/index.ts
With some minor fixups to address recent changes
> chore(graphql): bump to latest schema

- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
The userId field is long deprecated, and should be removed
> fix: remove supplied userId

- src/components/Campaigns/CloneCampaign.tsx
- src/form/fragmentUtil.ts
Missed userId meant to be removed in: https://github.com/brave/ads-ui/pull/1265
> fix(graphql): remove other reference of userId

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/user/settings/UserForm.tsx
- src/validation/RegistrationSchema.tsx
- src/validation/UserSchema.test.ts
- src/validation/UserSchema.tsx
Users cannot update their own email address. This is enforced server-side, so would have always failed.
> fix: only permit updating profile full name and password

- src/basic-attention-token/BasicAttentionTokenLandingPage.tsx
- src/components/Campaigns/CloneCampaign.tsx
- src/components/Datagrid/renderers.tsx
- src/form/fragmentUtil.ts
- src/graphql-client/graphql.ts
- src/graphql/ads-serve.graphql.schema.json
- src/i18n.ts
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/settings/UserForm.tsx
- src/user/views/adsManager/types/index.ts
- src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
- src/validation/RegistrationSchema.tsx
- src/validation/UserSchema.test.ts
- src/validation/UserSchema.tsx
- ???feat(translations): localization of ads-ui
Co-authored-by: Ian Krieger <iandkrieger@gmail.com>
- #1260
- #1259
- #1265
- #1268
- #1263
- #1262
> Production Release 2024-07-23

- lingui.config.ts
- package.json
- pnpm-lock.yaml
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
Removes annoyance of file changing every time there is line number difference
> chore(lingui): remove origins and line numbers in po file

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
Runs https://lingui.dev/ref/cli#extract-clean on po files
> chore(lingui): remove comments from po files

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/user/settings/NewKeyPairModal.tsx
Fixes https://github.com/brave/ads-ui/issues/1274
> fix: use correct verbiage for new private key

- src/auth/components/UserRedirect.tsx
- src/auth/views/components/AuthContainer.tsx
No need to land on the login pages if you are already authenticated
> fix(pages): redirect to dashboard if user is authenticated

- src/components/Campaigns/CampaignDateRange.tsx
- src/user/library/index.test.ts
- src/user/library/index.ts
- src/user/views/adsManager/types/index.ts
- src/util/campaign.ts
- src/validation/CampaignSchema.test.ts
- src/validation/CampaignSchema.tsx
Resolves https://github.com/brave/ads-ui/issues/1011
> fix(budget): allow someone to extend end date without having to edit budget

- src/auth/hooks/queries/useAuthorize.ts
- src/auth/lib/index.ts
- src/auth/views/AuthVerify.tsx
- src/auth/views/MagicLink.tsx
- src/auth/views/components/AuthContainer.tsx
Introduce better Anti-CSRF protections by prompting the user to make sure that every login request is an intentional request.
---
https://github.com/user-attachments/assets/e45b9f94-7246-4601-b63a-bc8a859f85f0
> feat(login): obtain user consent when verifying magic link

- src/auth/registration/Register.tsx
Fixes redirect not being honored
> fix: order of redirects is incorrect

- src/auth/hooks/queries/useAuthorize.ts
- src/auth/lib/index.ts
- src/auth/registration/Register.tsx
- src/auth/views/AuthVerify.tsx
- src/auth/views/MagicLink.tsx
- src/auth/views/components/AuthContainer.tsx
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
> Production Release 2024-08-06

- src/checkout/hooks/useValidatePaymentSession.ts
- src/checkout/lib/index.ts
PUT request should have a body, not qs params
> chore(request): PUT should have body, not qs params

- src/components/Creatives/hooks/useSubmitCreative.tsx
Name updates should be passed to server
> fix(creative): make sure name changes are passed to the backend

- src/auth/components/AdvertiserDetailsForm.tsx
- src/graphql-client/gql.ts
- src/graphql-client/graphql.ts
- src/graphql/ads-serve.graphql.schema.json
Updating naming conventions to match other ads manager specific graphql mutations
> chore(graphql): update mutation naming convention

- src/user/library/index.ts
> Production Release 2024-08-16

- index.html
resolves: [1322](https://github.com/brave/ads-ui/issues/1322)
> fix: add meta description

- src/checkout/hooks/useCreatePaymentSession.ts
- src/checkout/lib/index.ts
- src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
The way campaigns were updated has changed, we need to make sure if a person wants to change their payment method they can
> fix(payment): allow switching between payment methods

- package.json
Currently no actionable resolution: https://github.com/advisories/GHSA-952p-6rrq-rcjv
> chore(deps): temporarily ignore micromatch

- src/App.tsx
- src/basic-attention-token/BasicAttentionTokenLandingPage.tsx
Temporarily redirect BAT offer until discounts have been discussed in depth
> chore(BAT): temporarily redirect landing page

- src/App.tsx
Getting a blank page when merging 2 PR's together. This should fix.
> fix: wrap main component in suspense for lazy load

- src/App.tsx
- src/auth/registration/Register.tsx
- src/auth/views/Login.tsx
- src/auth/views/MagicLink.tsx
- src/basic-attention-token/BasicAttentionTokenLandingPage.tsx
- src/search/SearchLandingPage.tsx
- src/search/preview/SearchPreviewPage.tsx
- src/user/User.tsx
- vite.config.mts
> Production Release 2024-08-28

- src/auth/registration/SearchForm.tsx
- src/search/SearchLandingPage.tsx
Resolves issue where mobile view has misaligned text
https://github.com/user-attachments/assets/238c2065-5c5d-4694-bc81-68700000138b
> fix(search landing page): properly set width for mobile devices

- src/search/SearchLandingPage.tsx
- src/search/SearchTalkingPoints.tsx
> Production Release 2024-09-04

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/user/views/adsManager/views/advanced/components/campaign/fields/PaymentMethodField.tsx
> fix: account balance wording

- src/components/Creatives/CreateCreativeButton.tsx
> Production Release 2024-10-11

- src/components/Url/UrlResolver.tsx
- src/user/views/adsManager/types/index.ts
We can no longer pass multiple payloads to the backend, this accommodates that
> fix(creative): dont pass multiple payloads

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/search/SearchTalkingPoints.tsx
Resolves https://github.com/brave/ads-ui/issues/1378
> feat(search): update talking point verbiage

- package.json
- pnpm-lock.yaml
Fixes vulnerability in cross-spawn library
> fix(deps): cross-spawn

- package.json
- pnpm-lock.yaml
- src/user/views/adsManager/views/advanced/components/campaign/fields/PaymentMethodField.tsx
> Production Release 2024-11-19

- src/checkout/hooks/useIncreaseCampaignBudget.ts
- src/checkout/lib/index.ts
- src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
https://github.com/user-attachments/assets/3820a225-02dc-4f45-8f4b-c6821e44448e
> feat(payments): allow for budget increases

- CODEOWNERS
With our best wishes and huge thanks, of course!
> chore: remove Ian from CODEOWNERS

- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
> fix: extract recent translations

- eslint.config.js
- package.json
- pnpm-lock.yaml
- src/ErrorBoundary.tsx
- src/components/Datagrid/renderers.tsx
- src/components/Error/ErrorDetail.tsx
- src/form/DateFieldHelpers.tsx
- src/index.tsx
- src/user/User.tsx
- src/user/reporting/csv.library.tsx
- src/user/views/user/search/CreateSearchCampaign.tsx
- src/util/billingType.ts
Which has a number of breaking changes, see https://github.com/lingui/eslint-plugin/releases/tag/0.8.0
This is the change that is breaking #1403.
> chore: upgrade eslint-plugin-lingui

- src/components/Location/LocationPicker.tsx
- src/components/Navigation/AccountMenu.tsx
Resolves https://github.com/brave/ads-serve/issues/4555
While I'm there, sort the list by name rather than code (because code just looks odd).
And fix one of the react warnings.
> fix: exclude Japan from targetable country list

- package.json
- pnpm-lock.yaml
To address GHSA-968p-4wvh-cqc8
> chore(deps): upgrade babel

- src/components/Button/FormatHelp.tsx
Resolves https://github.com/brave/ads-ui/issues/1458
> fix: updates ads-format url

- src/auth/registration/VerticalPicker.tsx
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
There seems to be an issue displaying the verticals filed. This PR suggests a fix for that.
> fix: translation issue fix for verticals field

- src/auth/context/auth.interface.ts
- src/auth/hooks/mutations/useSignIn.ts
- src/auth/index.tsx
- src/auth/lib/index.ts
- src/components/Drawer/MiniSideBar.tsx
- src/components/Navigation/Navbar.tsx
- src/graphql-client/graphql.ts
- src/graphql/ads-serve.graphql.schema.json
- src/locales/en.po
- src/locales/es.po
- src/locales/pt.po
- src/locales/test.po
- src/search/preview/SearchPreviewPage.tsx
- src/user/User.tsx
This PR intends to add the functionality of general advertiser notifications/messages.
Sample screenshot image:
> feat: advertiser messages
