brave/ads-ui

src/user/analytics/analyticsOverview/AnalyticsOverview.tsx
https://github.com/brave/ads-ui/pull/593 introduced an error message, but additionally restricted the campagn formats that analytics can be viewed for.
This reverts the second half of that change: analytics can be viewed, as previously, for all campaign formats other then NTP SI.
=> Revert additional restriction on campaign format analytics

src/user/analytics/analyticsOverview/AnalyticsOverview.tsx
This isn't great, and there're more improvements to be made here, but at least we're not just displaying a broken-looking blank screen.
Re Improve loading time & user feedback on campaign analytics page #604
=> Display a loading indicator on analytics page

src/user/views/adsManager/views/advanced/lib/Library.tsx
^ not totally clear in that screenshot, but the "publish campaign" button *is* disabled.
Longer term there's a much wider overhaul of the validation required as [we've done in the internal dashboard](https://github.com/brave/ads-admin-dashboard/tree/master/src/validation) to make this sensibly testable. But this change addresses the pressing issue. 
Re #607
Note to reviewers: this PR is to put live on the staging environment - you will need to run this locally if you want to explore its behaviour. A subsequent PR will promote from staging to live.
=> Allow only URLs with https protocol during campaign creation

src/components/List/CustomListItemText.tsx, src/components/Url/UrlResolver.tsx, src/graphql/types.ts, src/graphql/url.generated.tsx, src/graphql/url.graphql, src/user/library/index.ts, src/user/views/adsManager/types/index.ts, src/user/views/adsManager/views/advanced/components/ads/AdField.tsx, src/user/views/adsManager/views/advanced/components/review/components/AdReview.tsx, src/validation/CampaignSchema.tsx
Validates target url for self service, displays errors below URL if they are present.
Review form asks that the check the ad, as you can get to review form before url finishes validating.
=> validate creative target url

.gitignore, src/user/analytics/AnalyticsOverview.tsx
Until we've moved to P3A based reporting.
See https://bravesoftware.slack.com/archives/C02BB9HAR5Y/p1680685813029169
=> Don't show NTP SI metrics

.vscode/settings.json, src/user/campaignList/CampaignList.tsx
This link was a normal <a href=> which means it forced a full page reload.  Now navigates without relation in the web app. I also changed it so it doesn't show a non-working link when the campaign in not under review.
Also deleted the vscode settings file I apparently accidentally added many months ago...
=> fix: make reporting campaign link not reload

src/form/PersistFormValues.tsx, src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx
Unable to reliantly reproduce on staging, but consistently reproduce locally: refreshing wipes local storage. Was able to reproduce in quick succession refreshing on staging.
This seems to reliably keep the form in localstorage
=> fix: only persist values once the form has been dirtied

.github/workflows/deploy-to-production.yml, .github/workflows/deploy-to-staging.yml, .github/workflows/sanity-check.yml, audit-resolve.json, package-lock.json, package.json
npm audit claimed there was a fix for the CVE below, however after the command was ran, nothing was actually fixed and the vulnerability still remained. Replace regular `npm audit` with the audit-resolve dep, so we can ignore faulty fixes / blocking dependencies when needed.
```
word-wrap  *
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap
optionator  0.8.3 - 0.9.1
Depends on vulnerable versions of word-wrap
node_modules/escodegen/node_modules/optionator
node_modules/optionator
```
=> fix(deps): use npm-audit-resolver for npm audits

src/components/Campaigns/Status.tsx
Should check campaign is active, before showing a status of "scheduled"
=> fix: check campaign is active for label

src/auth/hooks/mutations/useRegister.ts, src/auth/registration/Register.tsx, src/form/PersistRegistrationValues.tsx
Adds persisting registration form on refreshes / when there is an error.
=> feat: persist registration form on refresh and error

src/auth/context/auth.interface.ts, src/auth/hooks/queries/useUser.ts, src/auth/index.tsx, src/auth/registration/Register.tsx, src/auth/views/LandingPage.tsx, src/auth/views/Login.tsx, src/auth/views/MagicLink.tsx, src/components/AppBar/LandingPageAppBar.tsx, src/components/Card/CardContainer.tsx, src/components/Drawer/MiniSideBar.tsx, src/components/Navigation/DraftMenu.tsx, src/components/Navigation/Navbar.tsx, src/components/Steps/ActionButtons.tsx, src/graphql/types.ts, src/graphql/user.generated.tsx, src/graphql/user.graphql, src/theme.tsx, src/user/User.tsx, src/user/hooks/useGenerateApiKey.tsx, src/user/settings/NewKeyPairModal.tsx, src/user/settings/Profile.tsx, src/user/settings/Settings.tsx, src/user/settings/UserApiKey.tsx, src/user/settings/UserForm.tsx, src/user/views/user/CampaignView.tsx, src/user/views/user/Profile.tsx, src/validation/UserSchema.test.ts, src/validation/UserSchema.tsx
Front end portion of: https://github.com/brave/ads-serve/issues/3049
As well as meets partial goal of: https://github.com/brave/roadmap/issues/838
Allows user to update their email and add password, as well as create an API key to use advertiser API.
---
https://github.com/brave/ads-ui/assets/48930920/91f7623e-53d1-4691-a13c-5673b2c13678
---
=> feat: add user profile & refactor to sidebar

src/auth/views/LandingPage.tsx, src/components/AppBar/LandingPageAppBar.tsx, src/components/Drawer/MiniSideBar.tsx
Shares support menu, adds new resource, and makes it more obvious what to do if existing advertiser
---
=> fix: add new support resources

src/user/adSet/AdSetList.tsx, src/user/library/index.test.ts, src/user/library/index.ts, src/user/views/adsManager/types/index.ts, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx, src/user/views/adsManager/views/advanced/components/review/components/CampaignReview.tsx, src/util/billingType.ts
Correctly report the billing type for CPV campaigns, and do not break if additional billng types are added in the future.
However, intentionally we do not yet support this billing type for self-service created campaigns.
Re https://github.com/brave/ads-serve/issues/3255
=> feat: support reporting on CPV campaigns

src/user/adSet/AdSetList.tsx, src/user/library/index.test.ts, src/user/library/index.ts, src/user/views/adsManager/types/index.ts, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx, src/user/views/adsManager/views/advanced/components/review/components/CampaignReview.tsx, src/util/billingType.ts
=> Production Release 2023-08-23

src/user/hooks/useAdvertiserCreatives.ts, src/user/library/index.test.ts, src/user/library/index.ts
Makes sure createdAt shows correctly on `AdSetAds` screen
=> fix: correctly include createdAt

src/auth/registration/NameField.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx, src/user/views/adsManager/views/advanced/components/form/components/PaymentButton.tsx
Noticed some small discrepancies for advertisers with different permissions
=> fix: ui tweaks for setting own price

src/form/FormikHelpers.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/FormatField.tsx, src/user/views/adsManager/views/advanced/components/form/components/PaymentButton.tsx, src/validation/CampaignSchema.tsx
https://github.com/brave/ads-ui/assets/48930920/767ed1f7-1796-4176-8c0e-c055a878f01d
=> fix: different news CPM

package-lock.json, package.json, src/components/Campaigns/CloneCampaign.tsx, src/user/library/index.test.ts, src/user/library/index.ts, src/user/views/user/CampaignView.tsx
=> Production Release 2023-09-15

src/components/Assets/hooks/useGetImagePreviewUrl.ts, src/user/analytics/analyticsOverview/reports/campaign/EngagementsOverview.tsx
=> Production Release 2023-09-20

src/form/fragmentUtil.ts, src/graphql/advertiser.generated.tsx, src/graphql/advertiser.graphql, src/graphql/types.ts, src/user/hooks/useAdvertiserWithPrices.tsx, src/user/library/index.test.ts, src/user/views/adsManager/types/index.ts, src/user/views/adsManager/views/advanced/components/campaign/CampaignSettings.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/FormatField.tsx, src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx, src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx, src/user/views/adsManager/views/advanced/components/form/components/BaseForm.tsx, src/validation/CampaignSchema.test.ts, src/validation/CampaignSchema.tsx
front end of https://github.com/brave/ads-serve/pull/3379
---
https://github.com/brave/ads-ui/assets/48930920/3a09acc3-84ac-4a97-b742-45ef4a4f10f5
=> feat: allow price per advertiser

package-lock.json
Fixes:
```
postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix`
node_modules/postcss
1 moderate severity vulnerability
```
=> fix: PostCSS audit

src/user/analytics/renderers/index.tsx
Makes data display in tables consistent
---
=> fix: show dash when no data for all cases

src/components/Drawer/MiniSideBar.tsx, src/user/views/adsManager/views/advanced/components/adSet/NewAdSet.tsx
Pins settings to bottom, so that if missing features it is less apparent
---
=> fix: pin settings to bottom bar

src/form/fragmentUtil.ts, src/graphql/ad-set.generated.tsx, src/graphql/ad-set.graphql, src/graphql/advertiser.generated.tsx, src/graphql/analytics-overview.generated.tsx, src/graphql/campaign.generated.tsx, src/user/library/index.test.ts
- `execution` is long obsolete
- search adset properties are not (yet) required
=> chore: remove fields from queries not required by the code

.github/workflows/stale.yaml
Like we do on other repositories.
=> chore: add stale tracking for old issues and PRs

src/user/views/adsManager/views/advanced/components/adSet/fields/PickerFields.tsx, src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx
Segment config should not be available.
=> fix: segment config is unavailable for news

src/components/Creatives/CreativeList.tsx, src/components/Creatives/hooks/useSubmitCreative.tsx, src/components/Drawer/MiniSideBar.tsx, src/components/Navigation/Navbar.tsx, src/user/User.tsx, src/user/ads/InlineContentAd.tsx, src/user/ads/NotificationAd.tsx
Rename external facing "Creative" verbiage to "Ads"
=> fix: use Ads verbiage over creative verbiage

src/components/Creatives/CreateCreativeButton.tsx, src/user/hooks/useAdvertiserCreatives.ts, src/user/library/index.test.ts, src/user/library/index.ts, src/user/views/adsManager/views/advanced/components/adSet/fields/AdSetAds.tsx
Fixes when switching ad types, the ads from different types being part of the campaign
---
https://github.com/brave/ads-ui/assets/48930920/d735f801-9dd4-4b6d-a81c-31183952fd79
=> fix: make sure ads are relevant to campaign format

src/form/FormikHelpers.tsx, src/graphql/types.ts, src/user/hooks/useAdvertiserWithPrices.tsx, src/user/library/index.test.ts, src/user/views/adsManager/types/index.ts, src/user/views/adsManager/views/advanced/components/campaign/CampaignSettings.tsx, src/user/views/adsManager/views/advanced/components/campaign/components/BillingModelSelect.tsx, src/user/views/adsManager/views/advanced/components/campaign/components/CustomPriceSelect.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx, src/user/views/adsManager/views/advanced/components/campaign/fields/FormatField.tsx, src/user/views/adsManager/views/advanced/components/form/NewCampaign.tsx, src/user/views/adsManager/views/advanced/components/form/components/BaseForm.tsx, src/util/billingType.ts, src/util/campaign.ts, src/validation/CampaignSchema.test.ts, src/validation/CampaignSchema.tsx
Allows for an advertiser to choose between multiple billing types for a campaign
---
https://github.com/brave/ads-ui/assets/48930920/e4e64081-5144-4062-822b-7357ee32e411
=> feat: add support for multiple billing types

src/components/AppBar/LandingPageAppBar.tsx, src/components/Drawer/MiniSideBar.tsx
Updates links to point to ads-help.brave.com
---
=> feat: change links in support section

package.json, vite.config.mts
Resolves: SVG export from figma appears to no longer work on build of static assets
=> fix: svg breaks build CSS

src/components/Datagrid/stringFilterOperators.tsx, src/user/campaignList/CampaignList.tsx
You cannot view reporting or any details on NTT in dashboard. Filter these by default.
MUI does not provide an `is not` operator, so we needed to create one.
---
=> feat: filter NTT by default

src/checkout/lib/index.ts
Should use new payments endpoints as defined in https://github.com/brave/ads-serve/pull/3668
=> fix: transition to payments endpoints

src/graphql/advertiser.generated.tsx, src/graphql/advertiser.graphql, src/graphql/types.ts
This is not used, but will break in future backend changes if not removed
=> chore: remove mailing address from graphql

src/components/Segment/SegmentPicker.tsx, src/user/adSet/AdSetList.tsx, src/user/views/adsManager/views/advanced/components/review/components/AdSetReview.tsx, src/util/segment.ts
Now that we have update segment casing, It makes sense that categories do not need a dash in them
=> feat: make segment names fit better in their category

src/validation/CampaignSchema.tsx
Conversion URL check should validate more than just trailing slash
=> fix: add more conversion url validation

src/graphql/types.ts, src/user/library/index.test.ts, src/user/library/index.ts, src/user/views/adsManager/types/index.ts
On campaign creation, rely on default values for for `pacingStrategy` and `type`
Re https://github.com/brave/ads-serve/issues/3675
Relies on https://github.com/brave/ads-serve/pull/3677
=> chore(graphql): rely on default values

src/auth/components/AdvertiserDetailsForm.tsx, src/auth/components/types.ts, src/graphql/advertiser.generated.tsx, src/graphql/advertiser.graphql, src/validation/AdvertiserSchema.tsx
Resolves issue where an advertiser can already have an address
---
https://github.com/brave/ads-ui/assets/48930920/09f9f758-eef5-4f4e-925c-20578ba28635
=> fix: make sure form initializes with existing address

src/auth/components/AdvertiserAddress.tsx, src/auth/components/AdvertiserDetailsForm.tsx, src/validation/AdvertiserSchema.tsx
Fixes issue where an advertiser may not be able to agree because they were missing required address details
---
https://github.com/brave/ads-ui/assets/48930920/4ca83b62-d574-4340-a789-e5bdb3311d8a
=> fix: make sure advertiser can specify address

renovate.json
https://github.com/brave/renovate-config/pull/3 disabled this in the company config. Re-enable for this project.
=> chore: re-enable renovate major updates

src/auth/registration/AccountChoice.tsx
=> fix: replace "ad campaign types" link on https://ads.brave.com/register

src/validation/RegistrationSchema.test.ts, src/validation/RegistrationSchema.tsx
So that we can apply a more sophisticated version of these rules server-side only.
=> feat(search): remove client-side domain validation

src/components/Creatives/CreativeList.tsx, src/user/analytics/search/AdSetBreakdown.tsx
The new version of data grid stopped cells automatically being display: "flex" for layout performance reasons. Enforce this for those cells that need it.
Before:
After:
Before:
After:
=> fix: minor layout fixes after data grid update

src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/user/views/user/search/Finalize.tsx
Apparently if you don't do this you get junk displayed after deployment. Going forward we need to make this less error-prone. But for now just run `npm run extract`.
Also fix a typo that I noticed while reviewing.
=> fix: extract translations

crowdin.yml
We link to crowdin directly using a github connection, so the crowdin cli tools (and configuration of project & access token) are not required.
Once this is merged we may need to force a resync from the crowdin side.
=> chore(i18n): add in crowdin configuration file

src/user/library/index.test.ts, src/user/library/index.ts, src/user/views/adsManager/views/advanced/components/form/EditCampaign.tsx
Sending certain values if they have not changed can have unintended side effects. Send only if changed.
=> fix: send budget and dates only if changed

src/validation/CampaignSchema.tsx
The server no longer requires the "untargeted" segment configured, it adds it by default. So no need to validate that at 1 segment exists.
=> fix: remove min segments validation

src/auth/registration/AccountChoice.tsx, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po
None of our ad formats are sub-premium, so this wording is misleading.
=> feat: adjust wording on campaign type selection screen

src/auth/views/LandingPage.tsx
Adds extra spacing at top of screen
---
=> fix: add extra spacing at top of screen

src/basic-attention-token/BasicAttentionTokenLandingPage.tsx, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/search/SearchLandingPage.tsx, src/search/SearchTalkingPoints.tsx
Update copy based on feedback on the Search and Basic Attention token landing pages
---
=> feat: Search and BAT copy updates

src/routes/campaigns/analytics/AnalyticsOverview.tsx, src/routes/campaigns/analytics/breakdowns.tsx, src/routes/campaigns/analytics/filters/BreakdownSelector.tsx, src/user/views/user/CampaignReportViewSelector.tsx, src/user/views/user/reports/ConsultAccountManager.tsx, src/user/views/user/reports/OriginalCampaignReportView.tsx, src/user/views/user/reports/SearchCampaignReportView.tsx
Resolves lumping all reports into one matomo event, while also fixing ad set names and breakdown selections
=> bug: properly attribute reporting, fix breakdown selections

src/components/Creatives/CreativeType.tsx, src/components/Creatives/hooks/useGetCreativeDetails.tsx, src/components/Creatives/hooks/useSubmitCreative.tsx, src/components/Datagrid/renderers.tsx, src/graphql-client/graphql.ts, src/graphql/ads-serve.graphql.schema.json, src/graphql/creative.graphql, src/user/library/index.test.ts, src/user/views/adsManager/types/index.ts
Notably the type code simplifications in https://github.com/brave/ads-serve/pull/4019.
I haven't done a full switchover to use `typeCode` rather than `type.code`, and so therefore we're still dependent on that deprecated field. But this at least means we can regenerate the graphql definitions.
=> refactor: update based on graphql schema changes

src/components/Conversion/ConversionDisplay.tsx, src/components/Conversion/ConversionFields.tsx, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/user/views/adsManager/types/index.ts, src/user/views/adsManager/views/advanced/components/adSet/fields/ConversionField.tsx, src/user/views/user/CampaignView.tsx, src/user/views/user/ConversionAlert.tsx
Lets the end user know conversions have stricter enforcement:
---
=> feat: add a dismissible conversion change warning

package.json, pnpm-lock.yaml, src/App.tsx, src/components/Creatives/SearchPreview.tsx, src/components/Navigation/AccountMenu.tsx, src/search/preview/CallToAction.tsx, src/search/preview/LandingPageDetail.tsx, src/search/preview/LandingPageList.tsx, src/search/preview/LandingPageListEntry.tsx, src/search/preview/NoPreviewAvailable.tsx, src/search/preview/SearchPreviewPage.tsx, src/search/preview/SearchPreviewResults.tsx, src/search/preview/SummaryPanel.tsx, src/search/preview/data.ts, src/user/views/user/search/LandingPageDetail.tsx
For a limited set of hand-picked domains, provide access to a preview of the creatives we would run.
This is an early version and still requires additional features.
Re https://github.com/brave/ads-serve/pull/4085
Depends on https://github.com/brave/ads-serve/pull/4099
https://github.com/user-attachments/assets/fd3ba723-0121-4532-badd-aeb3d2bcac8a
=> feat(search): preview of creatives for large target advertisers

src/search/preview/data.ts
The default of swr is to refresh the data on screen activation, network reconnect etc. This is not needed for the search preview data as the data is very unlikely to change within one user session, generating needless requests that return the same data.
See https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations
=> fix: don't refresh search preview data

src/search/preview/SummaryPanel.tsx, src/search/preview/data.ts
Closes https://github.com/brave/ads-serve/issues/4151
=> feat(search-preview): include total landing page count

src/components/Creatives/CreateCreativeButton.tsx, src/components/Creatives/CreativeForm.tsx, src/components/Creatives/CreativeSelect.tsx, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/user/ads/AdsExistingAd.tsx, src/user/ads/InlineContentAd.tsx, src/user/ads/NotificationAd.tsx, src/user/views/adsManager/views/advanced/components/adSet/fields/AdSetAds.tsx
During testing for another PR, I noticed that when adding or creating a new creative, it adds to all ad sets. We should only add it to the one we are editing.
---
https://github.com/user-attachments/assets/77bbb89a-036d-41d4-abec-ad6321dbd8f7
=> fix(creatives): make sure selected creatives are correct for the ad set

src/auth/components/UserRedirect.tsx, src/auth/views/components/AuthContainer.tsx, src/components/Creatives/CreateCreativeButton.tsx, src/components/Creatives/CreativeForm.tsx, src/components/Creatives/CreativeSelect.tsx, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/user/ads/AdsExistingAd.tsx, src/user/ads/InlineContentAd.tsx, src/user/ads/NotificationAd.tsx, src/user/views/adsManager/views/advanced/components/adSet/fields/AdSetAds.tsx
=> Production Release 2024-08-01

src/user/views/user/CampaignView.tsx
Alert was removed, but the container was not.
Fix related to: https://github.com/brave/ads-ui/pull/1292
=> fix: remove outer container that had conversion alert in it

src/auth/registration/Register.tsx, src/auth/registration/SearchForm.tsx, src/auth/registration/SearchRegister.tsx, src/basic-attention-token/PrivacyPolicy.tsx, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/search/SearchLandingPage.tsx, src/search/SearchTalkingPoints.tsx
Resolves https://github.com/brave/ads-ui/issues/1296
---
https://github.com/user-attachments/assets/9aeba052-7b2e-48ec-bedd-fe3582f786b9
=> feat(search): update landing page to encompass talking points & registration

src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po
Missed translations from https://github.com/brave/ads-ui/pull/1302
ran `pnpm extract`
=> fix: missed translations in auth flow

pnpm-lock.yaml, renovate.json
We'd got a few pointless old dependencies referenced.
Run `pnpm dedupe` manually to remove, and update the renovate config to run this automatically.
=> build: dedupe dependencies

src/user/library/index.ts
Price should be transformed, vs just passing the raw price
Fixes the below image:
---
=> fix(price): we need to account for CPM in toAdd

src/search/preview/SummaryPanel.tsx
The price shown on this screen can be misleading as it is heavily estimated. Avoid this confusion.
As requested by @lukaslevert / @jpschmetz
=> feat(search preview): don't show an estimated price

src/search/preview/SummaryPanel.tsx
=> Production Release 2024-08-20

src/checkout/lib/index.ts
Payment types are capital, we need them to be lowercase
Fix for: https://github.com/brave/ads-ui/pull/1327
=> fix(payments): lowercase payment method

src/search/SearchLandingPage.tsx, src/search/SearchTalkingPoints.tsx
Talking points are currently at edge of screen, lets fix that
=> fix(search landing page): get talking points off edge of screen

package.json, pnpm-lock.yaml
https://github.com/advisories/GHSA-9wv6-86v2-598j
The proposed fix for this breaks react-router, but since a redos attack on a client side web app only breaks the attackers browser, just ignore the audit warning.
=> chore(audit): ignore path-to-regexp outputs backtracking regular expressions

package.json, pnpm-lock.yaml, src/search/preview/CallToAction.tsx, src/search/preview/SearchPreviewPage.tsx, src/search/preview/SearchPreviewResults.tsx, src/search/preview/SummaryPanel.tsx, src/search/preview/options.test.ts, src/search/preview/options.ts
Permit hiding of estimates and book a meeting, whilst not necessarily making this obvious from the link.
So:
- append a string of characters to the slug including an "l" to hide the meeting invite link (think: l = link)
- append a string of characters to the slug including an "0" to hide the estimates (think: 0 = no numbers)
Although we currently use 15 characters for the slug, don't force this. But do assume that we'll continue avoiding lookalike characters if the slugs got > 15 chars.
=> feat(search-preview): tweaks to search preview

package.json, pnpm-lock.yaml
Addresses https://github.com/advisories/GHSA-gcx4-mw62-g8wm
Also address GHSA-9wv6-86v2-598j since we figured out how to apply this fix correctly.
=> fix(audit): upgrade rollup

src/form/fragmentUtil.ts, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/validation/CampaignSchema.tsx
We have moved to only setup campaigns as postclick, however cloning a campaign can run into issues where this is not the case. Clone only as postclick.
=> fix(clone): conversions should only be postclick

src/components/Creatives/hooks/useSubmitCreative.tsx, src/user/library/index.test.ts, src/user/library/index.ts
While we still use the creative type code when pulling the campaign, we do not need it to pass to the server. This removes passing it to the server.
=> chore(creative): remove passing a specific type to the server

src/components/Creatives/CreateCreativeButton.tsx
We removed type from create, did not realize that this also passed it
=> fix(creative): make sure type is not passed with button

src/components/Creatives/CreateCreativeButton.tsx, src/validation/CreativeSchema.tsx
By removing pieces of initial creative, I also removed dimensions. Use existing function to get correct payload & dimensions
=> fix(creative): for news creatives, we still need dimensions

src/validation/CampaignSchema.tsx
Resolves issue where old campaigns with this value can fail validation
=> fix(validation): relax conversion type validation for backwards compatibility

src/user/views/adsManager/views/advanced/components/campaign/fields/PaymentMethodField.tsx
I had a balance of `0.00136`. We do not need to show account balance info ox in such cases.
=> fix: nominal balances should not show account balance modal

.github/workflows/codeql-analysis.yml, CODEOWNERS, package.json, pnpm-lock.yaml, src/checkout/hooks/useIncreaseCampaignBudget.ts, src/checkout/lib/index.ts, src/locales/en.po, src/locales/es.po, src/locales/pt.po, src/locales/test.po, src/user/views/adsManager/views/advanced/components/campaign/fields/BudgetField.tsx
- #1395
- #1400
- #1396
- #1398
=> Production Release 2024-11-22

package.json, pnpm-lock.yaml
pnpm [has this functionality built in](https://pnpm.io/cli/run#running-multiple-scripts) (and better output too, esp with an interactive terminal).
So remove use of this dependency.
=> build: remove npm-run-all2

.npmrc, renovate.json
1. update renovate config to not change `overrides`, as this forms useful documentation of which vulns we are specifically avoiding (this should autoclose https://github.com/brave/ads-ui/pull/1442)
2. add auto-install directive to .npmrc to avoid wasting dev time forgetting to call `pnpm install` after `git pull`
=> chore: renovate + npmrc

renovate.json
It's very distracting to get renovate PRs during the working day, as we try to keep to "PR zero" to reduce the amount of wasted effort not yet delivering value. A constant stream of renovate PRs throughout the day also encourages ignoring them, a poor outcome.
Also, bring across from our other repos the clearer phrasing of the config to prevent updating of the override ranges.
=> chore(renovate): adjust schedule
